## Indexing and Slicing

This also follows zero based indexing like python lists

### 1D Arrays

One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences. The <b>(start:stop:step)</b> notation for slicing is used

In [2]:
import numpy as np

In [3]:
a = np.arange(11)**2

In [4]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [5]:
a[2]

4

In [6]:
a[-2]

81

In [7]:
a[2:7]

array([ 4,  9, 16, 25, 36])

In [10]:
a[2:-2]

array([ 4,  9, 16, 25, 36, 49, 64])

In [11]:
a[2:]

array([  4,   9,  16,  25,  36,  49,  64,  81, 100])

In [12]:
a[:7]

array([ 0,  1,  4,  9, 16, 25, 36])

In [13]:
a[:11:2]

array([  0,   4,  16,  36,  64, 100])

In [14]:
a[::-1]

array([100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0])

### 2D Arrays

Consider an array students, it contains the test scores in two courses of the students against their names

In [30]:
students = np.array([['Alice','Beth','Cathy','Dorothy'],
                     [65,78,90,81],
                     [71,82,79,92]])

In [32]:
students

array([['Alice', 'Beth', 'Cathy', 'Dorothy'],
       ['65', '78', '90', '81'],
       ['71', '82', '79', '92']], dtype='<U7')

In [33]:
students[0]

array(['Alice', 'Beth', 'Cathy', 'Dorothy'], dtype='<U7')

In [34]:
students[1]

array(['65', '78', '90', '81'], dtype='<U7')

In [35]:
students[2]

array(['71', '82', '79', '92'], dtype='<U7')

In [36]:
students[0,1]

'Beth'

#### 2D Array slicing
This will consider the rows 0 and 1, columns 2 and 3

In [40]:
students[0:2,2:4]

array([['Cathy', 'Dorothy'],
       ['90', '81']], dtype='<U7')

##### All rows and column 1

In [41]:
students[:,1:2]

array([['Beth'],
       ['78'],
       ['82']], dtype='<U7')

##### All rows, columns 1 and 2

In [42]:
students[:,1:3]

array([['Beth', 'Cathy'],
       ['78', '90'],
       ['82', '79']], dtype='<U7')

##### All columns, rows 0 and 1

In [44]:
students[0:2,:]

array([['Alice', 'Beth', 'Cathy', 'Dorothy'],
       ['65', '78', '90', '81']], dtype='<U7')

##### All rows and columns

In [54]:
students[:]

array([['Alice', 'Beth', 'Cathy', 'Dorothy'],
       ['65', '78', '90', '81'],
       ['71', '82', '79', '92']], dtype='<U7')

##### The last row

In [51]:
students[-1,:]

array(['71', '82', '79', '92'], dtype='<U7')

##### 3rd from last to second from last row, last two columns

In [55]:
students[-3:-1,-2:]

array([['Cathy', 'Dorothy'],
       ['90', '81']], dtype='<U7')

### dots or ellipsis(...)

Slicing can also include ellipsis (…) to make a selection tuple of the same length as the dimension of an array. The dots (...) represent as many colons as needed to produce a complete indexing tuple

##### Equivalent to students[0] or students[0:1,:]
Select row 0 and all columns

In [58]:
students[0,...] 

array(['Alice', 'Beth', 'Cathy', 'Dorothy'], dtype='<U7')

##### All rows and column 1

In [54]:
students[...,1]

array(['Beth', '78', '2'], dtype='<U7')

In [59]:
students[...,1].shape

(3,)

In [60]:
students[:,1:2].shape

(3, 1)